### ISSUE TITLE
Template not refreshed when modified

### ISSUE THREAD

**Issue by taliesinpenbardd** [astronomersiva/lego#130]
Hey,

I'm trying my hand to Lego (you really should change that name :) ) and it's awesome so far.

I'm just running into a slight inconvenience: my `index.html` file calls for a `navbar.html` file. When I modify the `navbar.html` file, the lego server refreshes the web page, but without modifications (when it's all right for the `index.html` && `style.css` modifications). Each time, I have to relaunch `lego s` to see the `navbar.html` changes... 

Am I missing something ? A configuration option ? Something like `composer dumpautoload` that comes with npm ?

Thanks by advance !

**Comment by astronomersiva** [comment]
Thanks @taliesinpenbardd!

> When I modify the navbar.html file, the lego server refreshes the web page, but without modifications (when it's all right for the index.html && style.css modifications). Each time, I have to relaunch lego s to see the navbar.html changes

That sounds strange. Can you confirm if manually refreshing the page reflects the change? I have seen this in my project at times when the live server doesn't reflect the changes and a manual refresh seems to fix it.  If this is not the case and you are forced to restart the server each time, please share a reproduction repo so that I can look into this.

**Comment by astronomersiva** [comment]
@taliesinpenbardd I have fixed this in v3.1.1. It should work now. Sorry about the issue, please keep the feedback coming.

PS: I have a few new names in mind, will soon rename this project 😄

**Comment by taliesinpenbardd** [comment]
I can confirm, it's all good! Thank you for your reactivity.
